### ISSUE TITLE
Installing via composer.json

### ISSUE THREAD

**Issue by kappuccino** [kunalvarma05/dropbox-client#1]
The install command is not working
```
$ composer require kunalvarma05/dropbox-client
[InvalidArgumentException]
Could not find package kunalvarma05/dropbox-client at any version for your minimum-stability (stable).
Check the package spelling or your minimum-stability
```

but writing a simple composer.json file works
```
{
  "require": {
    "kunalvarma05/dropbox-client": "dev-master"
  }
}
```

then `composer install`

maybe you should update the readme.md file according to this issue.

your API is the only one for PHP running dropbox api v2... pretty cool !

**Comment by kunalvarma05** [comment]
Tagged v0.1. Running `composer require kunalvarma05/dropbox-client` would install the `v0.1` tag. :)
